name: curriculum-builder
region: nyc

# Backend API Service
services:
  - name: api
    github:
      repo: MikeBasse/Curriculum-Bilder-
      branch: main
      deploy_on_push: true
    source_dir: backend
    dockerfile_path: backend/Dockerfile
    http_port: 3001
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /api
    health_check:
      http_path: /api/health
      initial_delay_seconds: 10
      period_seconds: 30
      timeout_seconds: 10
      success_threshold: 1
      failure_threshold: 3
    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3001"
      - key: DATABASE_URL
        scope: RUN_TIME
        value: ${db.DATABASE_URL}
      - key: JWT_SECRET
        scope: RUN_TIME
        type: SECRET
      - key: REFRESH_SECRET
        scope: RUN_TIME
        type: SECRET
      - key: CLAUDE_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: FRONTEND_URL
        scope: RUN_TIME
        value: ${APP_URL}

# Frontend Static Site
static_sites:
  - name: web
    github:
      repo: MikeBasse/Curriculum-Bilder-
      branch: main
      deploy_on_push: true
    source_dir: frontend
    build_command: npm install && npm run build
    output_dir: dist
    routes:
      - path: /
    envs:
      - key: VITE_API_URL
        scope: BUILD_TIME
        value: ${APP_URL}/api

# Managed PostgreSQL Database
databases:
  - name: db
    engine: PG
    version: "15"
    size: db-s-dev-database
    num_nodes: 1
